export const mevzuatTitle = "YETKİLENDİRİLMİŞ GÜMRÜK MÜŞAVİRLİĞİ TEBLİĞİ";

export const mevzuatCitation = "Ticaret Bakanlığından: 10.09.2020 tarih ve 31240 sayılı R.G.";

export const mevzuatAmendmentCitation = "Son değişiklik: 11.01.2024 tarih ve 32426 sayılı R.G.";

export const mevzuatSourceUrl = "https://www.gumruk.com.tr/files/yetkilendirilmis_gumruk_musavirligi_tebligi_31240.htm";

export const mevzuatAmendmentUrl =
  "https://www.gumruk.com.tr/files/yetkilendirilmis_gumruk_musavirligi_tebliginde_degisik_32426.htm";

export const mevzuatParagraphs: string[] = [
  "BİRİNCİ BÖLÜM",
  "Amaç, Kapsam, Dayanak ve Tanımlar",
  "Amaç",
  "MADDE 1",
  "– (1) Bu Tebliğin amacı, yetkilendirilmiş gümrük müşavirliği sisteminin daha etkin ve verimli işlemesini sağlayacak açıklama ve düzenlemeleri belirlemektir.",
  "Kapsam",
  "MADDE 2",
  "– (1) Bu Tebliğ, yetkilendirilmiş gümrük müşaviri olabilme şartlarına, yetki belgesi ile ilgili işlemlere, yetkilendirilmiş gümrük müşavirince yapılacak tespit işlemlerine ve yetkilendirilmiş gümrük müşavirlerinin görev ve sorumlulukları ile bunların yerine getirilmemesi halinde uygulanacak işlemlere ilişkin usul ve esasları kapsar.",
  "Dayanak",
  "MADDE 3",
  "– (1) Bu Tebliğ, 27/10/1999 tarihli ve 4458 sayılı Gümrük Kanununun 10 uncu ve 226 ncı maddeleri ile 7/10/2009 tarihli ve 27369 mükerrer sayılı Resmî Gazete'de yayımlanan Gümrük Yönetmeliğinin 574 üncü maddesine dayanılarak hazırlanmıştır.",
  "Tanımlar",
  "MADDE 4",
  "– (1) Bu Tebliğin uygulanmasında;",
  "a) Bakanlık: Ticaret Bakanlığını,",
  "b) Genel Müdürlük: Gümrükler Genel Müdürlüğünü,",
  "c) Gümrük müşaviri: Eşyanın gümrükçe onaylanmış bir işlem veya kullanıma tabi tutulmasına ilişkin gümrük işlemlerini dolaylı temsil yoluyla takip eden, sonuçlandıran ve kendilerine Bakanlıkça gümrük müşaviri izin belgesi verilen kişiyi,",
  "ç) Günlük rapor: Sayım tutanakları ve diğer önemli olaylara ilişkin bilgileri içeren ve yetkilendirilmiş gümrük müşavirince sunulan raporu,",
  "d) Olumlu tespit raporu: Yetkilendirilmiş gümrük müşavirince gerçekleştirilen tespit işlemleri sonucunda, tespit raporlarının sonuç bölümü için rehberde öngörülen tüm bilgileri içerecek şekilde, olumlu görüşü ihtiva eden raporu,",
  "e) Olumsuz tespit raporu: Yetkilendirilmiş gümrük müşavirince gerçekleştirilen tespit işlemleri sonucunda olumsuz görüşü ihtiva eden raporu,",
  "f) Sistem: Bakanlıkça hazırlanan ve internet ortamında erişimi elektronik olarak sağlanan Yetkilendirilmiş Gümrük Müşaviri Sistemini,",
  "g) Rehber: Bu Tebliğin uygulanmasına ilişkin her türlü usul ve esasın belirlendiği Genel Müdürlükçe yayımlanan yetkilendirilmiş gümrük müşavirliği rehberini,",
  "ğ) Şartlı tespit raporu: Yetkilendirilmiş gümrük müşavirince gerçekleştirilen tespit işlemleri sonucunda, rapor kapsamında ortaya konulması gereken tespitlerden birinin ya da bazılarının, raporun sonuç bölümünde yer alan nihai görüşün olumlu olmasını engelleyecek şekilde yapılamadığı durumları ihtiva eden raporu,",
  "h) Tespit işlemi: Bu Tebliğ kapsamında yetkilendirilmiş gümrük müşavirince yapılacak tespit işlemlerini,",
  "ı) Tespit raporu: Yetkilendirilmiş gümrük müşaviri tarafından tespit işlemleri için gerekli inceleme ve araştırmanın tamamlanmasının ardından şekil ve içeriği rehberde yer alan rehberin ilgili bölümlerinde belirtilen usul ve esaslara uygun şekilde düzenlenecek raporu,",
  "i) Tespit sözleşmesi: Yetkilendirilmiş gümrük müşaviri ile yükümlü arasında özel hukuk hükümlerine istinaden yapılan sözleşmeyi,",
  "j) Vekâlet bildirgesi: Yetkilendirilmiş gümrük müşavirinin yetki belgesi çerçevesinde yaptığı işlemlerin vekil tarafından yapılmasına yetki verdiği, vekilin ise bu işlemleri yerine getirmeyi taahhüt ettiği ve bir örneği Ek-3'te yer alan belgeyi,",
  "k) Vekil: Bu Tebliğ kapsamında yetkilendirilmiş gümrük müşavirinden istenilen vekâlet bildirgesinde vekil olarak gösterilmiş yetkilendirilmiş gümrük müşavirini,",
  "l) Yetki belgesi: Adına düzenlendiği gümrük müşavirinin bu Tebliğ kapsamında tespit ve raporlama işlemlerini yapmaya yetkili olduğunu gösteren belgeyi,",
  "m) Yetki numarası: Yetkilendirilmiş gümrük müşavirinin tespit ve raporlama işlemlerini yaparken kullandığı numarayı,",
  "n) Yetkilendirilmiş gümrük müşaviri: Bu Tebliğ kapsamındaki tespit işlemlerini yapan ve sonucunda tespit raporu düzenleyen, Bakanlıkça adına yetki belgesi düzenlenen gerçek kişi veya tüzel kişi ortağı gümrük müşavirini,",
  "o) Yükümlü: Bu Tebliğ kapsamındaki tespit işlemlerini yaptırmak üzere yetkilendirilmiş gümrük müşaviri ile sözleşme imzalayan kişiyi, ifade eder.",
  "İKİNCİ BÖLÜM",
  "Yetkilendirilmiş Gümrük Müşavirinin Sahip Olması Gereken Nitelikler, Yetki Belgesi Başvurusu, Yetki Belgesine İlişkin İşlemler",
  "Yetkilendirilmiş gümrük müşavirinin sahip olması gereken nitelikler",
  "MADDE 5",
  "– (1) 11 inci maddede belirlenen tespit işlemlerini yapacak gümrük müşavirinin yetkilendirilmiş gümrük müşaviri olabilmesi için Gümrük Yönetmeliğinin 576 ncı maddesinin birinci fıkrasında yer alan niteliklere sahip olması gerekir.",
  "Yetki belgesi başvurusu",
  "MADDE 6",
  "– (1) Başvurular aşağıda belirtilen belgelerle birlikte Bakanlığa (Genel Müdürlüğe) yapılır:",
  "a) Ek-1'de yer alan ve eksiksiz doldurulmuş başvuru formu.",
  "b) Ek-2'de yer alan taahhütname.",
  "c) Ek-3'te yer alan vekâlet bildirgesi.",
  "e) Başvuru sahibi başvuru tarihinden önce, dolaylı temsil suretiyle gümrük müşavirliği hizmeti veren bir şirketin ortağı ise ortaklıktan ayrıldığını gösteren Türkiye Ticaret Sicili Gazetesi örneği veya ilgili ticaret sicil memurluğundan alınan belge aslı ya da örneği ile anonim şirketler için tescile esas ortaklık yapısını gösteren ortaklık kurulu kararı ya da noter onaylı pay defteri örnekleri.",
  "f) Tespit işlemlerinin tüzel kişilik bünyesinde yürütülmek istenilmesi durumunda, tüzel kişinin kuruluş, faaliyet alanı, ortaklık yapısı ve tüzel kişiliğe ortak olunduğunu gösteren Türkiye Ticaret Sicili Gazetesi örneği veya ilgili ticaret sicil memurluğundan alınan belge aslı ya da örneği ile anonim şirketler için tescile esas ortaklık yapısını gösteren ortaklık kurulu kararı ya da noter onaylı pay defteri örnekleri.",
  "g) Diploma veya mezuniyet belgesi örneği.",
  "(2) Yetki belgesi başvuruları, Bakanlık kayıtlarına alınmasının ardından en geç altmış gün içerisinde incelenerek sonuçlandırılır.",
  "Yetki belgesi",
  "MADDE 7",
  "– (1) 5 inci maddede yer alan nitelikleri taşıyan ve başvuruları uygun bulunan gümrük müşavirleri adına Genel Müdürlük tarafından Ek-4'te yer alan yetki belgesi düzenlenebilir.",
  "(2) Düzenlenen yetki belgesi gümrük müşavirinin KEP ve/veya elektronik tebligat adresi ile gümrük müşavirinin kayıtlı bulunduğu Gümrük ve Dış Ticaret Bölge Müdürlüğüne gönderilir.",
  "Yetki belgesinin yenilenmesi",
  "MADDE 8",
  "– (1) Yetki belgesinin geçerlilik süresi sonunda Bakanlığa yapılan başvurular değerlendirilerek şartları sağlayanlara ait belgeler yenilenebilir.",
  "(2) Yetki belgesi, aşağıdaki durumlarda belge süresinin dolması beklenilmeksizin yenilenir:",
  "a) Gerçek kişinin ad ve soyadında değişiklik olması.",
  "b) Ortağı olduğu tüzel kişiye ait vergi numarası veya ticaret unvanı bilgilerinde değişiklik olması.",
  "(3) Yetki belgesinin yenilenebilmesi için; 6 ncı maddenin birinci fıkrasında istenilen belgelere ek olarak yetki belgesinin yenilenmesini gerektiren durumu tevsik edici belgeler ile birlikte Genel Müdürlüğe başvuruda bulunulması gerekir.",
  "Yetki belgesinin değiştirilmesi",
  "MADDE 9",
  "– (1) Ortağı olunan firmanın değiştirilmesi durumunda Bakanlığa yapılacak başvurunun değerlendirmesi neticesinde yeni yetki belgesi düzenlenebilir.",
  "(2) Yetki belgesinin değiştirilebilmesi için 6 ncı maddenin birinci fıkrasında istenilen belgelere ek olarak duruma göre tüzel kişi ortaklığına girdiğini, ortaklıktan ayrıldığını veya ortaklıktan ayrıldığı ve yeni bir ortaklığa girdiğini gösteren Türkiye Ticaret Sicili Gazetesi örneği veya ilgili ticaret sicil memurluğundan alınan belge aslı ya da örneği ile anonim şirketler için tescile esas ortaklık yapısını gösteren ortaklık kurulu kararı ya da noter onaylı pay defteri örnekleri ile birlikte Genel Müdürlüğe başvuruda bulunulması gerekir.",
  "(3) İkinci fıkrada belirtilen belgelerin başvuru esnasında MERSİS'te olması halinde asılları veya noter onaylı örneklerinin sunulması talep edilmez.",
  "Yetki belgesinin iadesi",
  "MADDE 10",
  "– (1) Yetkilendirilmiş gümrük müşaviri, görevini devam ettirmek istememesi durumunda Genel Müdürlüğe bildirimde bulunur ve adına düzenlenmiş olan yetki belgesi Genel Müdürlükçe iptal edilir.",
  "(2) Yetki belgesini iade eden gümrük müşavirine bir yıl süreyle yetki belgesi verilmez.",
  "ÜÇÜNCÜ BÖLÜM",
  "Tespit İşlemi Yapılacak Gümrük İşlemleri, Tespit Ücreti, Genel Hükümler",
  "Tespit işlemi yapılacak gümrük işlemleri",
  "MADDE 11",
  "– (1) Yetkilendirilmiş gümrük müşaviri tarafından aşağıda belirtilen tespit işlemleri yapılır:",
  "a) Genel ve özel antrepolara ilişkin tespit işlemleri;",
  "1) AN1, antreponun açılmasına ilişkin başvuru dosyalarının ön incelemesini,",
  "2) AN2, antrepoda genişletme, daraltma işlemlerine ilişkin başvuru dosyalarının ön incelemesini,",
  "3) AN3, antrepodaki tadilatlara ilişkin başvuru dosyalarının ön incelemesini,",
  "4) AN4, antrepodaki adres değişikliğine ilişkin başvuru dosyalarının ön incelemesini,",
  "5) AN5, Gümrük Yönetmeliğinin 523 üncü maddesi çerçevesinde antreponun devir işlemlerinin mevzuata uygunluğunun incelenmesini,",
  "6) AN6, özel antrepoya eşya giriş çıkış işlemlerinin tespiti ile gümrük yükümlülüğü sona erdikten sonra varsa ilgili kurumlarca yapılacak kontrol sonuçlarına göre gümrük gözetiminin sonlandırılmasının tespitini,",
  "7) AN7, antrepoda stok kayıtlarının altışar aylık dönemler itibariyla tespitini,",
  "8) AN8, genel antrepoya eşya giriş çıkış işlemlerinin tespiti ile gümrük yükümlülüğü sona erdikten sonra varsa ilgili kurumlarca yapılacak kontrol sonuçlarına göre gümrük gözetiminin sonlandırılmasının tespitini,",
  "9) AN9, antrepo rejimine tabi eşyanın elleçleme işlemlerinin tespitini, kapsar.",
  "b) Geçici ithalat rejimine ilişkin tespit işlemleri;",
  "1) GC1, kısmi muafiyet suretiyle geçici ithalat rejimine konu eşya ile tam muafiyet suretiyle geçici ithalat rejimine konu mesleki teçhizat, ambalaj maddeleri, özel nitelikli eşya ve numunelere ilişkin süre uzatımı talebinde, eşyanın rejimin öngördüğü şekilde kullanılıp kullanılmadığının tespitini,",
  "2) GC2, ithalat vergilerinden tam muafiyet suretiyle geçici ithalat rejimine konu özel nitelikli eşyanın (kalıp, çizim, taslak ve benzeri diğer eşya, ölçme, kontrol, test araçları ve benzeri diğer eşya ile özel alet ve araçlar) kullanımı sonucunda elde edilen ürünlerin tamamının ya da öngörülen oranda Türkiye Gümrük Bölgesinden ihraç edildiğinin tespitini, kapsar.",
  "c) Gümrük kontrolü altında işleme rejimine ilişkin tespit işlemleri;",
  "1) GK1, gümrük kontrolü altında işleme rejimi kapsamında ibra işleminin tespitini,",
  "2) GK2, gümrük kontrolü altında işleme rejimi kapsamında ithal edilmiş ürünün nihai ürün içerisindeki miktarına ilişkin tespitini, kapsar.",
  "ç) NK1, eşyanın öngörülen süre dâhilinde nihai kullanıma tahsis edilip edilmediği ve öngörülen amaçlar için kullanılıp kullanılmadığının tespitini kapsar.",
  "d) Dâhilde işleme rejimine ilişkin tespit işlemleri;",
  "1) DR1, dâhilde işleme rejimi kapsamındaki eşyaya verilen izinlerle ilgili süre uzatımlarına esas teşkil edecek işlemlerin tespitini,",
  "2) DR2, dâhilde işleme izni kapsamında ithal edilen eşyanın ihraç edilen işlem görmüş ürünün bünyesinde kullanılıp kullanılmadığının teknik, bilimsel veya idareden kaynaklanan bir nedenle tespit edilememesi halinde yapılacak tespiti, kapsar.",
  "e) Menşe mevzuatına ilişkin tespit işlemleri;",
  "1) SK1, ibraz edildiği ithalatçı ülkeden sonradan kontrol talebiyle alınan A.TR Dolaşım Belgeleri ile 11/4/2023 tarihli ve 32160 sayılı Resmî Gazete'de yayımlanan Gümrük Genel Tebliği (Uluslararası Anlaşmalar) (Seri No: 10)'nin 4 üncü maddesinin birinci fıkrasının (j) bendinde sayılan tedarikçi beyanı hariç menşe ispat belgelerinin ilgili mevzuat çerçevesinde sonradan kontrol işlemlerinin yapılmasını,",
  "2) INF4, ithalatçı ülke gümrük idarelerinden kontrol talebiyle alınan kısa dönem ve/veya uzun dönem tedarikçi beyanlarının ilgili mevzuatları çerçevesinde kontrollerinin yapılarak, INF4 Bilgi Formu düzenlenmesine yönelik işlemlerin yapılmasını,",
  "3) AT1, Gümrük Kanunu ve dış ticaret mevzuatına uygun olarak ithal edildikten ve kullanıldıktan sonra ihraç edilmek istenilen eşya için A.TR Dolaşım Belgesi düzenlenmesinin söz konusu olduğu; ancak bu eşyanın ithaline ilişkin tevsik edici belgelerin, Gümrük Kanununun 13 üncü maddesinde yer alan 5 yıllık belge saklama süresinin geçmesi nedeniyle artık mevcut olmadığı hallerde, ihracatı ve yatırımları teşvik mevzuatı hükümleri ve ithalat rejiminin mahrecine iade hükümleri saklı kalmak ve eşyanın serbest dolaşımda olduğunu belirleyen ticari belge ve kayıtları ile eşyanın muhasebe kayıtlarının bulunduğu envanter defteri kayıtları esas alınarak serbest dolaşım statüsünün belirlenmesini,",
  "4) EU2, tercihli ticaret anlaşmaları çerçevesinde onaylanmış ihracatçı yetkisi başvurusuna konu eşyanın menşe kurallarına uygunluğunun tespitini, kapsar.",
  "f) Onaylanmış kişi statüsüne ilişkin tespit işlemleri; OK1, onaylanmış kişi statü belgesi müracaatına ilişkin başvuru dosyalarının ön incelemesini kapsar.",
  "g) Çok zor duruma ilişkin tespit işlemleri;",
  "1) ZD1, 21/7/1953 tarihli ve 6183 sayılı Amme Alacaklarının Tahsil Usulü Hakkında Kanunun 48 inci maddesi ve 21/1/2014 tarihli ve 28889 sayılı Resmî Gazete'de yayımlanan Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No:2)'nin 20 ve 21 inci maddeleri gereğince, tecil ve taksitlendirme talebinde bulunan yükümlülerin çok zor durumda olup olmadıklarının tespitini kapsar.",
  "ğ) Beyannamenin belirli alanlarında yapılacak düzeltmeye ilişkin tespit işlemleri;",
  "1) BD1, Gümrük Kanununun 73 üncü maddesinin ikinci fıkrası uyarınca beyannamede yapılacak düzeltme işlemlerinin, rehberde yer alan usul ve esaslar dikkate alınarak ön incelemesini kapsar.",
  "h) Takas işlemlerinde KKDF muafiyeti uygulanmasına ilişkin tespit işlemleri;",
  "1) TK1, Takas kapsamında yapılan ithalat ve ihracat işlemlerinin farklı gümrük idarelerinden yapılması halinde KKDF muafiyeti uygulanmasına esas teşkil edecek tespitleri kapsar.",
  "ı) MH1, metal hurda olarak beyan edilen eşyanın firma tesisinde yapılacak işlem sonucunda başka bir eşya haline gelip gelmediğinin tespitini kapsar.",
  "i) TP1, kapanmış beyannamelerde 31/12/2020 tarihli ve 3350 sayılı Cumhurbaşkanı Kararı ile yürürlüğe konulan İthalat Rejimi Kararının 4 üncü maddesinde sayılan önlemlere tabi eşyanın kapsam dışı olup olmadığının tespitini kapsar.",
  "j) DK1, diğer kurumlarca yapılacak kontroller kapsamında kullanım amacına göre bilgi/belgeye tabi eşyanın kullanım amacına uygun olup olmadığının tespitini kapsar.",
  "Tespit ücreti",
  "MADDE 12",
  "– (1) Yetkilendirilmiş gümrük müşavirleri, yapacakları tespit işlemlerine ilişkin hizmet karşılığı Gümrük Kanununun geçici 6 ncı maddesinin onuncu fıkrasına istinaden belirlenen yetkilendirilmiş gümrük müşavirliği asgari ücret tarifesini uygular.",
  "(2) Yetkilendirilmiş gümrük müşaviriyle yükümlü arasında belirlenecek ücretin takvim yılı bazında belirlenen ve hizmete konu iş ve işlemlerin gerçekleştirildiği yılı kapsayan asgari ücret tarifesinden az olmaması gerekir.",
  "Genel hükümler",
  "MADDE 13",
  "– (1) Genel ve özel antrepolara ilişkin tespit işlemlerinde;",
  "a) AN6 ve AN8 tespit işlemlerini yapacak yetkilendirilmiş gümrük müşaviri, antreponun her açılış kapanışı ile açık bulunduğu sürelerde eşyanın gümrük gözetimi altında bulundurulmasına yönelik gerekli tedbirleri alır. Antrepoların kapanışı sırasında antrepo giriş çıkış kapıları mühür altına alınır. Buna ilaveten, gümrük gözetimini zafiyete uğratacak hususlar ile antrepoda eksikliklerin tespiti halinde durumu her koşulda gümrük idaresine ve gerektiğinde antrepo işleticisine gecikmeksizin bildirir.",
  "b) AN6 ve AN8 tespit işlemlerine ilişkin olarak Ek-6'da yer alan günlük rapor düzenlenir.",
  "c) AN6, AN7 ve AN8 tespit işlemlerine ilişkin olarak yükümlü ile yetkilendirilmiş gümrük müşaviri arasındaki sözleşmenin bir yıl süreli olarak yapılması gerekir.",
  "ç) AN6 ve AN8 tespit işlemlerine ilişkin olarak yükümlü ile yetkilendirilmiş gümrük müşaviri arasındaki sözleşmenin herhangi bir nedenle bir yıldan daha kısa bir süre önce feshedilmesi halinde durum derhal ilgili yetkilendirilmiş gümrük müşaviri tarafından gerekçesi ile birlikte antrepoları denetimi altında bulunduran gümrük müdürlüğüne bildirilir. Sözleşmesi feshedilen ile sözleşme akdedilen yetkilendirilmiş gümrük müşavirlerince tarama suretiyle müştereken düzenlenen sayıma ilişkin devir-teslim tutanağı ilgili gümrük müdürlüğüne gönderilir. Sözleşmesi feshedilen yetkilendirilmiş gümrük müşavirinin mücbir sebepler nedeniyle sayıma iştirak edememesi halinde gümrük müdürlüğünce kurulacak heyet ve sözleşme akdedilen yetkilendirilmiş gümrük müşaviri tarafından tarama suretiyle antreponun sayımı yapılır ve dönemsel olarak stok kayıtlarına uygunluğu tespit edilerek tutanağa bağlanır. Tutanak sonucuna göre gerekli işlem tesis edilir.",
  "d) AN7 tespit işleminin dönemsel olarak yaptırılmadığı tespit edilen antreponun, bu antrepoyu denetimi altında bulunduran gümrük müdürlüğü tarafından, gümrük müdür yardımcısı başkanlığında en az üç kişiden oluşan bir heyet marifetiyle tarama suretiyle sayımı yapılır ve dönemsel olarak stok kayıtlarına uygunluğu tespit edilir.",
  "e) Yetkilendirilmiş gümrük müşaviri ile geçerli AN6, AN7 ve AN8 tespit sözleşmesi yapılmayan antrepolara; akaryakıt antrepoları, yolcu giriş ve çıkış kapılarındaki gümrüksüz satış mağazaları ve gümrük idarelerince işletilen antrepolar hariç olmak üzere, eşya girişine izin verilmez. Antrepolar ayrıca bağlı bulundukları gümrük müdürlüklerince yılda en az iki defa denetlenir.",
  "f) İlk kez bir yetkilendirilmiş gümrük müşaviri ile sözleşme yapılan antrepodaki eşyanın; antrepoda görev yapan gümrük memuru, yetkilendirilmiş gümrük müşaviri ve antrepo işleticisi firma ile müştereken tespiti yapılarak tutanağa bağlanır.",
  "g) AN6, AN8 ve AN9 tespit işlemlerinde rehberin ekinde yer alan sayım tutanağı düzenlenir.",
  "ğ) AN6 ve AN8 tespit işlemlerini yapacak yetkilendirilmiş gümrük müşaviri tarafından eşya çıkış işlemi yapılırken eşyanın Gümrük Yönetmeliğinin 181 inci maddesinin beşinci fıkrası kapsamında yer alıp almadığı ile eşyanın gümrük gözetiminin sonlandırılmasında bir sakınca olup olmadığı tespit edilir.",
  "h) Tespit işlemi yapılacak süre içinde antrepoya eşya giriş ve çıkışı olmaması halinde AN7 tespit raporu düzenlenmez.",
  "ı) Genel antrepolarda AN7, AN8 ve AN9 tespit işlemleri, özel antrepolarda ise AN6, AN7 ve AN9 tespit işlemlerinin aynı yetkilendirilmiş gümrük müşavirince yapılması zorunludur. Bunların dışında kalan tespit işlemleri için yükümlü aynı veya başka bir yetkilendirilmiş gümrük müşaviri ile sözleşme yapabilir.",
  "i) 8/8/2017 tarihli ve 30148 sayılı Resmî Gazete'de yayımlanan Gümrüksüz Satış Mağazaları Yönetmeliği hükümlerine göre açılmasına izin verilen depolar, diplomatik satış mağazaları, uçakta satış mağazaları ve gemilere eşya satış mağazaları için bu Tebliğ hükümleri çerçevesinde işlem yapılır. Gümrüksüz Satış Mağazaları Yönetmeliği hükümleri uyarınca yolcu giriş ve çıkış kapılarında açılışına izin verilen mağazalar için 11 inci maddenin birinci fıkrasının (a) bendinin",
  "(1), (2), (3), (4) ve (5) numaralı alt bentlerinde belirtilen tespit işlemleri bu Tebliğ hükümleri çerçevesinde; aynı bendin (6), (7), (8) ve (9) numaralı alt bentlerinde belirtilen tespit işlemleri ise gümrük müdürlüğünce yapılır.",
  "j) Bu Tebliğ hükümleri çerçevesinde yetkilendirilmiş gümrük müşaviri tarafından, antrepoya eşya giriş çıkış işlemlerinin tespiti için AN6 ya da AN8 tespit sözleşmesi imzalanmış olması halinde; antrepoya eşya getiren ve antrepodan eşya çıkaran araçlar için, Rehber ekinde yer alan araç kaydına uygun olarak plaka bilgileri yetkilendirilmiş gümrük müşaviri veya yetkilendirilmiş gümrük müşavirince çalıştırılan gümrük müşavir yardımcısı tarafından sisteme kaydedilir. Ancak, bu işlemle ilgili olarak tespit raporu düzenlenmez.",
  "(2) NK1 tespit işlemi ile ilgili olarak belirlenen asgari ücretin tespit raporuna konu nihai kullanım izin belgesi kapsamı eşya için alınan teminat miktarını aşması halinde bu Tebliğ hükümlerinin uygulanması zorunluluğu bulunmamaktadır. Bu hüküm, 89.08 tarife pozisyonunda yer alan “sökülecek gemilerle, suda yüzen sökülecek diğer araçlar” için uygulanmaz.",
  "(3) Dâhilde işleme iznine konu ithal eşyasının kıymetinin on bin Avro'yu aşmaması durumunda, DR1 tespit işleminin yapılması zorunluluğu bulunmamaktadır.",
  "(4) Bu Tebliğ hükümleri çerçevesinde yetkilendirilmiş gümrük müşaviri tarafından, bir antrepoya eşya giriş ve çıkışının tespiti için AN6 veya AN8 kodlu tespit sözleşmesi imzalanmış olması halinde;",
  "a) 31/12/2010 tarihli ve 27802 beşinci mükerrer sayılı Resmî Gazete'de yayımlanan Gümrük Genel Tebliği (TIR İşlemleri) (Seri No:1)'nin 33, 34 ve 35 inci maddelerinde yer alan, antrepoda görevli memurlarca yapılması öngörülen boşaltma, sonlandırma ve sevk işlemleri ile rehberde yer alan teslim tesellüm tutanağının düzenlenmesi işlemleri,",
  "b) Transit beyannamesine ilişkin varış, boşaltma ve bir sonraki boşaltma yerine sevk işlemleri, yetkilendirilmiş gümrük müşaviri veya yetkilendirilmiş gümrük müşavirince çalıştırılan gümrük müşavir yardımcısı tarafından yapılır. Yetkilendirilmiş gümrük müşavirleri, çalışma usul ve esasları ile yetki ve sorumlulukları bakımından bu Tebliğin genel hükümleri ile AN6 ve AN8 kodlu tespit işlemlerinin özel hükümlerine tabidir. Ancak, TIR ve transit işlemlerine ilişkin görevlerle ilgili olarak tespit raporu düzenlenmez.",
  "(5) Sonradan kontrole tabi ihraç eşyasına ilişkin toplam fatura bedelinin 10.000 ABD Dolarını aşmaması durumunda, SK1 tespit işleminin yapılması zorunluluğu bulunmamaktadır. Firmaların talep etmeleri durumunda bu kıymetin altındaki işlemler için de SK1 tespit işlemi yapılabilir.",
  "(6) İthalat vergilerinden tam veya kısmi muafiyet suretiyle geçici ithalata konu eşya ile gümrük kontrolü altında işleme rejimi kapsamı eşyaya ilişkin toplam fatura bedelinin 10.000 ABD Dolarını aşmaması durumunda GC1, GC2 ve GK1 tespit işleminin yapılması zorunluluğu bulunmamaktadır. Firmaların talep etmeleri durumunda bu kıymetin altındaki işlemler için de GC1, GC2 ve GK1 tespit işlemi yapılabilir.",
  "(7) ZD1 tespit işlemine ait tespit raporları Gümrük Genel Tebliği (Tahsilat İşlemleri) (Seri No:2), bu Tebliğ ve rehberde belirtilen usul ve esaslar dikkate alınarak hazırlanır.",
  "(8) Yetkilendirilmiş gümrük müşavirleri, görevlerinin ifası ile ilgili olarak, aralarındaki evlilik bağı ortadan kalkmış olsa dahi eşlerinin, üçüncü derece de dâhil olmak üzere kan veya kendisini oluşturan evlilik bağı ortadan kalkmış olsa dahi kayın hısımlarının iş ve işlemlerini gerçekleştiremezler.",
  "(9) Yetkilendirilmiş gümrük müşaviri olarak çalışmaya başlamadan önce antrepo işleticisi ile ortaklık ilişkisi içinde olanlar, bu ortaklık ilişkisinin bitirilmesinden itibaren iki yıl geçmedikçe aynı antreponun tespit işlemlerini yapamazlar.",
  "(10) OK1 kapsamında düzenlenen tespit raporlarının onaylanmış kişi statüsü mevzuatı uyarınca belirlenen formata uygun bir şekilde hazırlanmadığı, bilgi ve belgelerin eksik veya hatalı incelendiği, raporun belirlenen süreler içinde hazırlanmadığı ve tespit sözleşmesine taraf olan yetkilendirilmiş gümrük müşaviri ile olumlu tespit raporunu düzenleyen kişinin birbirinden farklı olması durumlarında;",
  "a) Gümrük idaresince tespit edilmesi halinde, tespit raporunu düzenleyen yetkilendirilmiş gümrük müşaviri yazılı olarak uyarılır. Bu durumun aynı takvim yılı içerisinde ikinci defa tespiti halinde, diğer mevzuat hükümleri saklı kalmak kaydıyla yetkilendirilmiş gümrük müşaviri hakkında 24 üncü madde uyarınca işlem yapılır.",
  "b) Bir yıl içerisinde üçüncü defa tespit edilmesi halinde; olumlu tespit raporunun gümrük idaresine sunulduğu tarihten itibaren altı ay boyunca yetkilendirilmiş gümrük müşavirinin OK1 kapsamında tespit raporu düzenlemesine izin verilmez ve diğer mevzuat hükümleri saklı kalmak kaydıyla yetkilendirilmiş gümrük müşaviri hakkında 24 üncü madde uyarınca işlem yapılır.",
  "(11) MH1, TP1 ve DK1 kapsamında düzenlenen tespit raporlarının ilgili mevzuatı uyarınca belirlenen formata uygun bir şekilde hazırlanmadığı, bilgi ve belgelerin eksik veya hatalı incelendiği, raporun belirlenen süreler içinde gümrük idaresine sunulmadığı hallerde;",
  "a) Yetkilendirilmiş gümrük müşaviri yazılı olarak uyarılır.",
  "b) Bu durumun aynı takvim yılı içerisinde ikinci defa tespitinde diğer mevzuat hükümleri saklı kalmak kaydıyla yetkilendirilmiş gümrük müşaviri hakkında 24 üncü madde uyarınca işlem yapılır.",
  "c) Bu durumun aynı takvim yılı içerisinde üçüncü defa tespitinde tespit raporunun gümrük idaresine sunulduğu tarihten itibaren altı ay boyunca yetkilendirilmiş gümrük müşavirinin MH1, TP1 ve DK1 kapsamında tespit raporu düzenlemesine izin verilmez ve diğer mevzuat hükümleri saklı kalmak kaydıyla yetkilendirilmiş gümrük müşaviri hakkında 24 üncü madde uyarınca işlem yapılır.",
  "DÖRDÜNCÜ BÖLÜM",
  "Tespit Sözleşmesi, Tespit Raporu, Çalışma Düzeni, Evrak İşlemleri, Gümrük Müşavir Yardımcısı Çalıştırma, Vekâlet",
  "Tespit sözleşmesi",
  "MADDE 14",
  "– (1) Yetkilendirilmiş gümrük müşaviri tarafından yapılacak her bir tespit işlemi için yükümlü ile ayrı bir tespit sözleşmesi yapılır.",
  "(2) Tespit sözleşmesi, Ek-5.A, Ek-5.B ve Ek-5.C'de yer alan örneğe uygun olarak sistem üzerinden düzenlenir. Sözleşmenin hazırlanmasında rehberde geçen usul ve esaslar ile asgari ücret tarifesi dikkate alınır.",
  "(3) Tüzel kişilik ortağı olarak faaliyet gösteren yetkilendirilmiş gümrük müşavirince düzenlenecek tespit sözleşmesi, tespit işlemini yapacak yetkilendirilmiş gümrük müşaviriyle birlikte, ortağı bulunduğu tüzel kişi adına söz konusu tüzel kişiyi temsil ve ilzama yetkili kişi ya da kişiler tarafından da imzalanır.",
  "Tespit sözleşmesinin elektronik ortamda gönderilmesi",
  "MADDE 15",
  "– (1) Yapılan tüm tespit sözleşmelerine ilişkin bilgiler yetkilendirilmiş gümrük müşaviri tarafından, sözleşmenin yapıldığı tarihten itibaren en geç yedi iş günü içinde sistem vasıtasıyla gönderilir. İptal veya feshedilen",
  "tespit sözleşmelerine ilişkin işlemler",
  "MADDE 16",
  "– (1) Tespit sözleşmesi;",
  "a) Yetki belgesinin iptali, geri alınması, değiştirilmesi veya iade edilmesi durumunda vekile ilişkin hükümler yerine getirildikten sonra,",
  "b) Tespit işlemine konu faaliyetin sona ermesi veya faaliyet alanının ortadan kalkması nedeniyle tespit işleminin yapılamayacağı durumda, iptal edilir.",
  "(2) Yeni sözleşmeye taraf olacak yetkilendirilmiş gümrük müşaviri, fiili durumu eski yetkilendirilmiş gümrük müşaviri ile birlikte ortak bir tutanağa bağlamak suretiyle işe başlar. Söz konusu tutanak ilgili gümrük müdürlüğüne gönderilir. Yeni sözleşme yapacak yetkilendirilmiş gümrük müşaviri mevzuata aykırı herhangi bir durumun tespiti halinde gerekçesi ile birlikte derhal ilgili gümrük müdürlüğüne sistem vasıtasıyla bildirimde bulunur.",
  "Tespit raporlarının sunulması",
  "MADDE 17",
  "– (1) 11 inci maddede belirtilen tespit işlemleri için bu Tebliğde ve rehberde belirtilen usul ve esaslara uygun olarak rapor düzenlenir. Yetkilendirilmiş gümrük müşavirince hazırlanan tespit raporu, ekleriyle birlikte sistem vasıtasıyla gönderilir.",
  "(2) Düzenlenen tespit raporu, aşağıda yer alan merci/mercilere belirlenen süreler içerisinde sunulur:",
  "a) AN7 tespit işlemine ilişkin olarak; genel ve özel antrepolar için Ocak-Haziran ve Temmuz-Aralık dönemlerini kapsayacak şekilde, her dönemi takip eden ayın son gününe kadar sunulur ve bir örneği yükümlüye verilir.",
  "b) AN6 ve AN8 tespit işlemlerine ilişkin olarak düzenlenen sayım tutanaklarında yer alan bilgiler sistem vasıtasıyla tespit işleminin yapıldığı gün gönderilir. AN6 ve AN8 tespit raporları aylık genel bir rapora bağlanarak, ekinde sayım tutanaklarıyla birlikte takip eden ayın ilk yedi iş günü içerisinde e-imza kullanılarak sistem vasıtasıyla gönderilir. Raporun bir örneği de yükümlüye verilir.",
  "c) SK1 tespit işlemlerine ilişkin olarak düzenlenmesi gereken tespit raporları, kontrol talebinde bulunan ülkenin talep yazısı tarihini müteakip en fazla beş ay içerisinde sunulur. INF4 tespit kodu kapsamındaki işlemlerde bu süre üç aydır.",
  "ç) (c) bendinde belirtilen işlemlerin aynı bentte belirtilen süreler zarfında tamamlanarak gerekli raporun sunulmaması halinde, durum ilgili gümrük müdürlüğünce varsa yetkilendirilmiş gümrük müşaviri ve tespit raporu düzenleten kişinin gerekçeli görüşü ile birlikte derhal Uluslararası Anlaşmalar ve Avrupa Birliği Genel Müdürlüğüne bildirilir. Anılan Genel Müdürlükçe yapılan değerlendirme sonucunda, kontrol talebinde bulunan ülke idaresine duruma göre ya olumsuz yönde yanıt verilir ya da gerekli tespit raporunun düzenletilmesi için en fazla bir aya kadar ek süre tanınır. Tespit raporunun verilen ek süre zarfında da sunulamaması halinde, kontrol talebinde bulunan ülke idaresine olumsuz yönde yanıt verilerek dosya kapatılır. Bu aşamadan sonra verilen raporlar ve yapılan itirazlar değerlendirmeye alınmaz.",
  "d) Sayım tutanakları ve diğer önemli olaylara ilişkin bilgiler esas alınarak hazırlanacak günlük rapor, tespit işleminin yapıldığı günün sonuna kadar yetkilendirilmiş gümrük müşaviri tarafından elektronik ortamda sunulur. Zorunlu durumlar sebebiyle bu sürede sunulamayan günlük raporun, bu durumun belgelendirilmesi kaydıyla, en geç tespit işleminin yapıldığı günü takip eden günün sonuna kadar sunulmasına Gümrük ve Dış Ticaret Bölge Müdürlüğünce izin verilebilir.",
  "e) OK1 tespit işleminin sözleşmenin yapıldığı tarihi izleyen otuz gün içerisinde olumlu veya olumsuz olarak rapora bağlanılması zorunludur. Bu süre geçirildikten sonra düzenlenen raporlar geçersizdir. Yapılan tespit neticesinde süresi içerisinde düzenlenen rapor olumluysa iki nüsha halinde, olumsuzsa bir nüsha halinde yükümlüye verilir.",
  "f) TK1 tespit işlemine ilişkin düzenlenen raporun bir örneği takas işlemlerinin bitirilmesi gereken süre sonundan itibaren en geç bir ay içerisinde sunulur ve bir örneği yükümlüye verilir.",
  "g) AN9 tespit raporunun bir örneği elleçlemeye ilişkin tutanağın sistem üzerinden gönderildiği tarihi takip eden ayın ilk yedi iş günü içerisinde sunulur, bir örneği tespit işlemini yaptıran kişiye verilir.",
  "ğ) GK2 tespit işlemlerine ilişkin olarak düzenlenmesi gereken tespit raporları, nihai ürünün serbest dolaşıma girmesinden itibaren bir ay içerisinde hazırlanıp takip eden ayın en geç 10'una kadar sunulur.",
  "h) DR2 tespit işlemlerine ilişkin olarak düzenlenmesi gereken tespit raporları, tespit raporu düzenlenmesi için gümrük idaresince firmaya tebligatta bulunulmasını müteakip en geç bir ay içerisinde sunulur.",
  "ı) DK1 tespit işlemlerine ilişkin olarak düzenlenmesi gereken tespit raporları, tespitin yapıldığı ayı takip eden ayın yedinci iş gününün bitimine kadar sunulur.",
  "i) MH1 ve TP1 tespit işlemlerine ilişkin düzenlenmesi gereken tespit raporları, tespit konusu işlemlerin bitirilmesi için gümrük idaresince verilen süre sonundan itibaren en geç bir ay içerisinde sunulur.",
  "Tespit raporları ve günlük rapora ilişkin gümrük idaresince yapılacak işlemler",
  "MADDE 18",
  "– (1) Tespit raporları, günlük rapor ve sayım tutanaklarında yer alan bilgiler idare tarafından kontrol edilir. Sayım tutanaklarında yer alan bilgilerle uyumlu olduğu saptanan günlük rapor ve tespit raporları sistem üzerinden onaylanır. Günlük raporda herhangi bir önemli olay yaşanmadığının bildirilmesi durumunda gümrük idaresince onay veya ret işlemi yapılmaz.",
  "(2) Tespit raporları ve günlük rapor ile ilgili sayım tutanaklarında yer alan bilgiler arasında uyumsuzluk veya hata olması durumunda rapor, gerekçesi belirtilmek suretiyle yetkilendirilmiş gümrük müşavirine iade edilir. Bu raporlar, hata veya uyumsuzluğun düzeltilmesi amacıyla en fazla iki defa iade edilebilir. Raporlardaki hata veya uyumsuzluğun iadeye rağmen düzeltilmemesi halinde 22 nci maddenin birinci fıkrasının (f) bendi hükmü çerçevesinde değerlendirme yapılarak cari işlemlerin devamlılığı sağlanır.",
  "(3) OK1 kapsamında düzenlenen tespit raporları, ancak yükümlü tarafından onaylanmış kişi statü belgesi için raporun düzenleme tarihini izleyen beş iş günü içerisinde müracaat edilmesi halinde değerlendirilmeye alınır.",
  "(4) AN6 ve AN8 tespit işlemlerine ilişkin olarak düzenlenen tutanaklarda yer alan bilgilerin tespitin yapıldığı gün sisteme girilmemesi halinde, sisteme girilmeyen tutanaklara ilişkin işlemler ilgili gümrük müdürlüğü tarafından gerçekleştirilir.",
  "Çalışma düzeni, evrak işlemleri ve dosyalama",
  "MADDE 19",
  "– (1) Yetkilendirilmiş gümrük müşavirince yapılacak tespit işlemleri, tespit işlemi kapsamındaki inceleme ve araştırmalar sırasında toplanan bilgileri ve yapılan tespit işleminin detayını içerecek şekilde düzenli bir kayıt ve dosyalama sistemi içinde gerçekleştirilir. Bu kayıt ve dosyalar, ilgili mevzuatta aksine bir hüküm bulunmadıkça elektronik ortamda da tutulabilir.",
  "(2) Her bir tespit işlemi için ayrı bir tespit dosyası açılır.",
  "(3) Açılan tespit dosyalarına sözleşme yılı/yetki numarası/tespit kodu/sözleşme sıra numarasını içerecek şekilde her yıl itibariyle müteselsil numara verilir.",
  "(4) AN6 ve AN8 tespit işlemlerinde, aynı gün içerisinde gerçekleşen tüm giriş ve çıkış işlemleri için tek bir tespit dosyası açılır.",
  "(5) Tespit işlemi kapsamında düzenlenen tutanaklar, yazışmalar, günlük rapor, tespit sözleşmesinin tarafı olan gerçek/tüzel kişi tarafından ibraz edilen belgeler ve hazırlanan tespit raporu bahsi geçen tespit dosyasında muhafaza edilir.",
  "(6) Tespit dosyalarında yer alacak bilgi ve belgeler, rehberin tespit işlemlerine ilişkin bölümlerinde belirtilen hususları da içermek, yapılacak tespit ve denetim işlemlerinde yetkili personele azami kolaylığı sağlayacak tertip ve düzeni içermek şartıyla, yetkilendirilmiş gümrük müşaviri tarafından belirlenir.",
  "(7) Yetkilendirilmiş gümrük müşavirince düzenlenen her bir tespit raporuna, içinde yer aldığı tespit dosyasının sayısı verilir.",
  "(8) Yükümlüler, günlük rapor ve 11 inci maddedeki tespit işlemleriyle ilgili bütün bilgi ve belgeleri yetkilendirilmiş gümrük müşavirine sunmak ve tespit işlemlerini kolaylaştıracak tedbirleri almak zorundadır.",
  "Gümrük müşavir yardımcısı çalıştırma",
  "MADDE 20",
  "– (1) Yetkilendirilmiş gümrük müşavirleri yanlarında çalışan gümrük müşavir yardımcılarının bilgileri işe başlama tarihinden itibaren yedi gün içinde sisteme kaydedilir.",
  "Vekâlet",
  "MADDE 21",
  "– (1) Yetki belgesinin iptali ve geri alınması durumlarında yetkilendirilmiş gümrük müşavirine bir takvim yılı içinde toplamda altmış günü aşmamak üzere vekil tayin edilir. Yetki belgesinin değiştirilmesi durumunda ise kullanılacak vekâlet süresi her olaya özgü olarak altmış günü geçmemek üzere Genel Müdürlükçe belirlenir.",
  "(2) İzin, hastalık ve benzeri durumlar nedeniyle geçici olarak mesleki faaliyete ara verilmesi gerektiğinde otuz günü aşmamak üzere vekil tarafından tespit işlemlerinin devamlılığı sağlanır. Mücbir sebeplerin varlığı halinde bu süre Genel Müdürlükçe uzatılabilir.",
  "(3) Süresinden önce feshedilen tespit sözleşmelerine ilişkin tespit işlemleri yeni sözleşme yapılıncaya kadar mevcut yetkilendirilmiş gümrük müşaviri veya vekili tarafından yürütülür. Bu süre otuz günü aşamaz.",
  "(4) Vekâleten işlem yapan yetkilendirilmiş gümrük müşaviri, gerçekleştirdiği tespit işlemlerinden tespit sözleşmesine taraf olan yetkilendirilmiş gümrük müşaviri ile birlikte müteselsilen sorumludur.",
  "BEŞİNCİ BÖLÜM",
  "Sorumluluk, Yetki Belgesinin Geri Alınması ve İptali, Cezai Hükümler",
  "Sorumluluk",
  "MADDE 22",
  "– (1) Yetkilendirilmiş gümrük müşavirleri aşağıda yer alan hususlardan sorumludur:",
  "a) Tespit raporlarını ve günlük raporu süresi içerisinde gümrük mevzuatına uygun olarak hazırlamak ve sunmak,",
  "b) Tespit işlemlerinin yapılması sırasında gümrük mevzuatına herhangi bir aykırılık tespit edilmesi veya böyle bir aykırılık bulunduğuna dair ciddi şüpheler oluşması halinde, derhal ilgili gümrük müdürlüğüne bildirimde bulunmak ve bu durumu günlük raporda belirtmek,",
  "c) Hazırlanan her türlü tespit raporunu ve eklerini, bunlara dayanak olan günlük rapor ve tespit sözleşmelerini, tespit işleminde kullanılan diğer tüm bilgi ve belgeleri istenildiğinde ibraz etmek üzere beş yıl süreyle muhafaza etmek,",
  "ç) Antrepolara eşya alınması ve çıkarılması sırasında eksiklik ve fazlalık tespit edilmesi halinde durumu antrepoda görevlendirilen gümrük müşavir yardımcısı ve antrepo işleticisi ile müştereken bir tutanağa bağlamak ve derhal ilgili gümrük idaresine bilgi vererek gerekli takibatın başlatılmasını sağlamak ve bu durumu günlük raporda bildirmek,",
  "d) Tespit işlemleri ile ilgili olarak belirlenen asgari ücret tarifesinin altında hizmet vermemek,",
  "e) Dolaylı temsil suretiyle faaliyet gösteren gümrük müşavirleri ya da tespit işlemini yaptıran yükümlüler ile doğrudan veya dolaylı iş ilişkisi içinde bulunmamak. İş ilişkisinin bulunduğunun kabul edileceği durumlar, bunlarla sınırlı olmamak üzere, aşağıda sayılmıştır:",
  "1) Yetkilendirilmiş gümrük müşavirinin, dolaylı temsil suretiyle iş takibi yapan gümrük müşaviri ve/veya tespit işlemini yaptıran yükümlü ile kira akdi olmaksızın aynı adreste faaliyet göstermesi,",
  "2) Yetkilendirilmiş gümrük müşavirinin, dolaylı temsil suretiyle iş takibi yapan gümrük müşaviri veya ortakları ile ortaklık ilişkisine girmiş olduğunun belirlenmesi,",
  "3) Yetkilendirilmiş gümrük müşavirinin tespit işlemini yaptıran yükümlü veya yükümlünün ortaklarıyla ortaklık ilişkisine girmiş olduğunun belirlenmesi,",
  "4) Yetkilendirilmiş gümrük müşavirliği şirketinin ortaklarından herhangi birinin tespit işlemini yaptığı kişiler ile ortaklık ya da çalışan statüde ilişki içinde bulunması,",
  "5) Yetkilendirilmiş gümrük müşaviri ile tespit işlemini yaptıran yükümlü arasında tespit işlemleri dışında karşılıklı hizmet faturası alışverişi yapılması veya iade fatura tanzim edilmesi, tespit işlemleri ile ilgisi bulunmayan karşılıklı/karşılıksız para veya ekonomik değer transferi yapılması,",
  "6) Tespit sözleşmesi gereği tespit yaptıran tarafından karşılanması gereken büro, ısınma, iletişim, elektrik gibi tespitle ilgili giderler için yetkilendirilmiş gümrük müşaviri tarafından ödeme yapılması,",
  "7) Yetkilendirilmiş gümrük müşavirince tespit işlemini yaptığı yükümlülere tespit işlemleri veya danışmanlık hizmeti dışında herhangi bir hizmet verilmesi, belge temin, takip ve kapatma gibi işlemler yapılması,",
  "8) Yetkilendirilmiş gümrük müşaviri tarafından dolaylı temsil suretiyle iş takibi yapan gümrük müşavirine bir hizmet verilmesi, bu kişiler arasında hizmet faturası alışverişi yapılması, karşılıklı/karşılıksız para veya ekonomik değer transferi yapılması.",
  "f) Yetkilendirilmiş gümrük müşavirleri tarafından, tespit işlemini yaptıran yükümlülere verilen danışmanlık hizmeti (e) bendi kapsamında değerlendirilmez. Halka açık şirketlerdeki ortaklıklarda (e) bendinin (2), (3), (4) numaralı alt bentlerinin uygulanabilmesi için söz konusu kişilerin şirketin yönetim veya denetim kurulunda görev alması ve/veya en az %10 hisseye sahip olması gerekir.",
  "g) Günlük rapor ve 11 inci maddede yer alan tespit işlemleri gerçekleştirilirken bir tespitle ilgili birden fazla hususta gümrük idaresinde gereksiz iş yüküne neden olacak şekilde düzeltme talebinde bulunmamak,",
  "ğ) Bu Tebliğ kapsamında elde edilen bilgi ve belgeleri bu Tebliğde öngörülen amaçlar dışında kullanmamak,",
  "h) Bu Tebliğ kapsamındaki tespit işlemlerinde yetki numarasını, adı, soyadı ve varsa tüzel kişi unvanını içeren kaşe kullanmak,",
  "ı) Mesleki ve akademik unvan dışında sahip olunan başka unvanları kullanmamak,",
  "i) Antrepolarda bir gün içerisinde sonlandırılan TIR karnesinin Volet-2 yapraklarının asılları ve eklerini Gümrük Genel Tebliği (TIR İşlemleri) (Seri No:1)'nin ekinde yer alan bordroya tescil numarasına göre kaydederek en geç on iş günü içerisinde antreponun bağlı bulunduğu gümrük idaresine göndermek,",
  "j) Yetkilendirilmiş gümrük müşaviri tarafından antrepoda sonlandırılan transit beyanına ilişkin belge ve bilgileri; boşaltma sonucunun uygun olması halinde boşaltma tarihinden itibaren en geç üç iş günü içerisinde, uygun olmaması halinde ise en geç boşaltma tarihini takip eden ilk iş günü içerisinde bir bordroya kaydederek antreponun bağlı bulunduğu gümrük idaresine göndermek,",
  "k) AN6 ve AN8 tespit işlemlerine ilişkin olarak düzenlenen tutanaklarda yer alan bilgileri tespitin yapıldığı gün sisteme girmek.",
  "Yetki belgesinin geri alınması ve iptali",
  "MADDE 23",
  "– (1) Yetkilendirilmiş gümrük müşavirinin Gümrük Kanununun geçici 6 ncı maddesi uyarınca meslekten çıkarma cezası ile cezalandırılması durumunda yetki belgesi geri alınır ve bu kişilere bir daha yetki belgesi düzenlenmez.",
  "(2) Sahte veya yanıltıcı bilgi ve belgelere dayanılarak alındığı anlaşılan yetki belgesi geri alınır. Bu kapsamda yetki belgesi geri alınanlar hakkında yasal işlemler yapılır ve bu kişilere bir daha yetki belgesi düzenlenmez.",
  "(3) Yetkilendirilmiş gümrük müşavirinin ölümü halinde yetki belgesi iptal edilir.",
  "Cezai hükümler",
  "MADDE 24",
  "– (1) Bu Tebliğin ilgili hükümlerine uyulmaması durumunda aşağıdaki cezai hükümler uygulanır:",
  "a) 13 üncü maddenin dördüncü fıkrası uyarınca yapılması öngörülen boşaltma, sonlandırma, sevk işlemleri ile teslim tesellüm tutanağının düzenlenmesi işlemlerinin mevzuata uygun şekilde yerine getirilmemesi durumunda Gümrük Kanununun 241 inci maddesine istinaden usulsüzlük cezası uygulanır.",
  "b) 13 üncü maddenin sekizinci ve dokuzuncu fıkralarına aykırı davranılması halinde, bu aykırılık düzeltilinceye kadar yetkilendirilmiş gümrük müşavirinin sistem üzerinde işlem yapması engellenir. Ayrıca Gümrük Kanununun 241 inci maddesine istinaden usulsüzlük cezası uygulanır.",
  "c) 13 üncü maddenin onuncu fıkrasına aykırı hareket edilmesi halinde Gümrük Kanununun 241 inci maddesine istinaden usulsüzlük cezası uygulanır.",
  "ç) 14 üncü maddenin ikinci fıkrasına aykırı hareket edilmesi halinde Gümrük Kanununun 241 inci maddesine istinaden usulsüzlük cezası uygulanır.",
  "d) 15 inci maddeye aykırı hareket edilmesi halinde Gümrük Kanununun 241 inci maddesine istinaden usulsüzlük cezası uygulanır.",
  "e) 20 nci maddeye aykırı hareket edilmesi halinde Gümrük Kanununun 241 inci maddesine istinaden usulsüzlük cezası uygulanır.",
  "f) 22 nci maddenin birinci fıkrasının (a) bendine aykırı hareket edilmesi halinde, her bir rapor için Gümrük Kanununun 241 inci maddesine istinaden usulsüzlük cezası uygulanır.",
  "g) 22 nci maddenin birinci fıkrasının (b), (c), (ç), (f), (h) ve (j) bentlerine aykırı hareket edilmesi halinde Gümrük Kanununun 241 inci maddesine istinaden usulsüzlük cezası uygulanır.",
  "ğ) 22 nci maddenin birinci fıkrasının (ı) ve (i) bentlerine uyulmaması halinde, her bir bordro için Gümrük Kanununun 241 inci maddesinin birinci fıkrası uyarınca işlem yapılır.",
  "h) Günlük raporun idareyi yanıltıcı biçimde düzenlenmesi halinde her bir günlük rapor için Gümrük Kanununun 241 inci maddesine istinaden usulsüzlük cezası uygulanır.",
  "ı) 13 üncü maddenin on birinci fıkrasında belirtilen durumlarda Gümrük Kanununun 241 inci maddesine istinaden usulsüzlük cezası uygulanır.",
  "(2) Birinci fıkrada sayılan hallerde usulsüzlük cezası uygulanması, Gümrük Kanununun geçici 6 ncı maddesinin uygulanmasına engel teşkil etmez.",
  "ALTINCI BÖLÜM",
  "Çeşitli ve Son Hükümler",
  "Yetki",
  "MADDE 25",
  "– (1) Bakanlık, bu Tebliğin uygulanmasını temin etmek amacıyla gerekli göreceği her türlü tedbiri almaya, özel ve zorunlu durumları inceleyip sonuçlandırmaya yetkilidir.",
  "(2) Bu Tebliğde yer almayan hususlarda gümrük mevzuatının ilgili hükümleri uygulanır.",
  "(3) Gümrük idareleri gerekli gördüğü takdirde, bu Tebliğ kapsamında yapılacak her türlü işlemi incelemeye yetkilidir.",
  "(4) Yetkilendirilmiş gümrük müşavirinin bulunmadığı Gümrük ve Dış Ticaret Bölge Müdürlüklerine bağlı antrepolarda gümrük memurları görevlendirilir.",
  "(5) Bu Tebliğde yer alan gümrük işlemleri, gereken hallerde kamu yararı ve hizmet gereği gözetilerek, Bakanlıkça her zaman gümrük memurları eliyle yürütülebilir.",
  "Yürürlükten kaldırılan tebliğ",
  "MADDE 26",
  "– (1) 7/10/2016 tarihli ve 29850 sayılı Resmî Gazete'de yayımlanan Gümrük Genel Tebliği (Yetkilendirilmiş Gümrük Müşavirliği) (Seri No:6) yürürlükten kaldırılmıştır.",
  "Geçiş hükmü",
  "GEÇİCİ MADDE 1",
  "– (1) Bu Tebliğin 20 nci maddesinde belirtilen gümrük müşavir yardımcılarına ilişkin bilgiler bu Tebliğin yayımı tarihinden itibaren yedi gün içinde sisteme kaydedilir.",
  "Yürürlük",
  "MADDE 27",
  "– (1) Bu Tebliğin;",
  "a) 13 üncü maddesinin birinci fıkrasının (b) bendi ile 17 nci maddesinin ikinci fıkrasının (d) bendi yayımı tarihinden iki ay sonra,",
  "b) Diğer hükümleri yayımı tarihinde, yürürlüğe girer.",
  "Yürütme",
  "MADDE 28",
  "– (1) Bu Tebliğ hükümlerini Ticaret Bakanı yürütür.",
];
